/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 30 06:39:38 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.common.base.Optional;
import java.util.Collection;
import java.util.Set;
import net.mooctest.Arborescence;
import net.mooctest.ChuLiuEdmonds;
import net.mooctest.Edge;
import net.mooctest.ExclusiveEdge;
import net.mooctest.Weighted;
import net.mooctest.WeightedGraph;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

public class ChuLiuEdmonds_ESTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChuLiuEdmonds chuLiuEdmonds0 = new ChuLiuEdmonds();
      WeightedGraph<ExclusiveEdge<Integer>> weightedGraph0 = (WeightedGraph<ExclusiveEdge<Integer>>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn((Collection) null).when(weightedGraph0).getNodes();
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.PartialSolution.initialize(weightedGraph0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.Partition", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WeightedGraph<Integer> weightedGraph0 = (WeightedGraph<Integer>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence(weightedGraph0, (Set<Edge<Integer>>) null, (Set<Edge<Integer>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.Edge", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WeightedGraph<Integer> weightedGraph0 = (WeightedGraph<Integer>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn((Collection) null).when(weightedGraph0).getNodes();
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.PartialSolution.initialize(weightedGraph0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.Partition", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      WeightedGraph<Integer> weightedGraph0 = (WeightedGraph<Integer>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn((WeightedGraph) null).when(weightedGraph0).filterEdges(nullable(com.google.common.base.Predicate.class));
      int int0 = 0;
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence(weightedGraph0, integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.ChuLiuEdmonds", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WeightedGraph<String> weightedGraph0 = (WeightedGraph<String>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn((WeightedGraph) null).when(weightedGraph0).filterEdges(nullable(com.google.common.base.Predicate.class));
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence(weightedGraph0, "k|V}");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.ChuLiuEdmonds", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      WeightedGraph<Object> weightedGraph0 = (WeightedGraph<Object>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn((WeightedGraph) null).when(weightedGraph0).filterEdges(nullable(com.google.common.base.Predicate.class));
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence(weightedGraph0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.ChuLiuEdmonds$PartialSolution", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      WeightedGraph<Arborescence<String>> weightedGraph0 = (WeightedGraph<Arborescence<String>>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn((Collection) null).when(weightedGraph0).getNodes();
      WeightedGraph<Arborescence<String>> weightedGraph1 = (WeightedGraph<Arborescence<String>>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn(weightedGraph0).when(weightedGraph1).filterEdges(nullable(com.google.common.base.Predicate.class));
      WeightedGraph<Arborescence<String>> weightedGraph2 = (WeightedGraph<Arborescence<String>>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn(weightedGraph1).when(weightedGraph2).filterEdges(nullable(com.google.common.base.Predicate.class));
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence(weightedGraph2, (Arborescence<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.Partition", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      WeightedGraph<Object> weightedGraph0 = (WeightedGraph<Object>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn((Collection) null).when(weightedGraph0).getNodes();
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.PartialSolution.initialize(weightedGraph0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.Partition", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      WeightedGraph<String> weightedGraph0 = (WeightedGraph<String>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn((Collection) null).when(weightedGraph0).getNodes();
      WeightedGraph<String> weightedGraph1 = (WeightedGraph<String>) mock(WeightedGraph.class, new ViolatedAssumptionAnswer());
      doReturn(weightedGraph0).when(weightedGraph1).filterEdges(nullable(com.google.common.base.Predicate.class));
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence(weightedGraph1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.Partition", e);
      }
  }
}
