/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 30 15:24:42 CST 2019
 */

package net.mooctest;


import org.junit.Test;

public class WeightedTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Weighted<String> weighted0 = null;
      try {
        weighted0 = new Weighted<String>("", 0.0);
       
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/base/Preconditions
         //
     
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        Weighted.weighted(object0, 0.0);
       
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/base/Preconditions
         //
     
      }
  }
}
