/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 30 05:45:27 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.Pair;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class PairTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Pair<String, String> pair0 = Pair.of("t-", "t-");
      boolean boolean0 = pair0.equals("t-");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Pair<String, String> pair0 = new Pair<String, String>("L", "L");
      Integer integer0 = new Integer((-4019));
      Pair<Object, Integer> pair1 = new Pair<Object, Integer>("L", integer0);
      boolean boolean0 = pair1.equals(pair0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Pair<String, Object> pair0 = Pair.of("com.google.common.base.Objects$1", (Object) "com.google.common.base.Objects$1");
      Pair<Object, Object> pair1 = new Pair<Object, Object>("com.google.common.base.Objects$1", "Pair{first=com.google.common.base.Objects$1, second=com.google.common.base.Objects$1}");
      Pair<Object, Pair<Object, Object>> pair2 = new Pair<Object, Pair<Object, Object>>(pair0, pair1);
      Pair pair3 = (Pair)pair2.first;
      boolean boolean0 = pair0.equals(pair3);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Pair<String, Object> pair0 = Pair.of("com.google.common.base.Objects$1", (Object) "com.google.common.base.Objects$1");
      Pair<Object, Object> pair1 = new Pair<Object, Object>("com.google.common.base.Objects$1", "Pair{first=com.google.common.base.Objects$1, second=com.google.common.base.Objects$1}");
      Pair<Object, Pair<Object, Object>> pair2 = new Pair<Object, Pair<Object, Object>>(pair0, pair1);
      boolean boolean0 = pair2.equals(pair0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer((-4019));
      Pair<Object, Integer> pair0 = new Pair<Object, Integer>("L", integer0);
      pair0.hashCode();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Integer integer0 = new Integer((-1488));
      Pair<String, Integer> pair0 = new Pair<String, Integer>("", integer0);
      Pair<Pair<String, Integer>, Integer> pair1 = Pair.of(pair0, integer0);
      String string0 = pair1.toString();
      assertEquals("Pair{first=Pair{first=, second=-1488}, second=-1488}", string0);
  }
}
