/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 30 05:15:30 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.common.base.Optional;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.ServiceLoader;
import java.util.Set;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import net.mooctest.Arborescence;
import net.mooctest.ChuLiuEdmonds;
import net.mooctest.DenseWeightedGraph;
import net.mooctest.Edge;
import net.mooctest.ExclusiveEdge;
import net.mooctest.SparseWeightedGraph;
import net.mooctest.Weighted;
import net.mooctest.WeightedGraph;
import org.junit.runner.RunWith;

public class ChuLiuEdmonds_ESTest {
 
  @Test(timeout = 1000)
  public void test5bf4ff07_6822_45b7_98ac_52614cd8711500()  throws Throwable  {
      TreeSet<Edge<Weighted<Edge<ExclusiveEdge<String>>>>> treeSet0 = new TreeSet<Edge<Weighted<Edge<ExclusiveEdge<String>>>>>();
      assertNotNull(treeSet0);
      
      LinkedHashSet<Edge<Weighted<Edge<ExclusiveEdge<String>>>>> linkedHashSet0 = new LinkedHashSet<Edge<Weighted<Edge<ExclusiveEdge<String>>>>>();
      assertEquals(0, linkedHashSet0.size());
      assertTrue(linkedHashSet0.isEmpty());
      assertNotNull(linkedHashSet0);
      
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence((WeightedGraph<Weighted<Edge<ExclusiveEdge<String>>>>) null, (Set<Edge<Weighted<Edge<ExclusiveEdge<String>>>>>) treeSet0, (Set<Edge<Weighted<Edge<ExclusiveEdge<String>>>>>) linkedHashSet0);
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertTrue(e instanceof NullPointerException);
      }
  }

  @Test(timeout = 1000)
  public void test1f8071dc_fae4_4f42_aa55_95189da2b3d304()  throws Throwable  {
      double[][] doubleArray0 = new double[1][3];
      DenseWeightedGraph<Integer> denseWeightedGraph0 = DenseWeightedGraph.from(doubleArray0);
      assertNotNull(denseWeightedGraph0);
      assertEquals(1, doubleArray0.length);
      
      TreeSet<Edge<Integer>> treeSet0 = new TreeSet<Edge<Integer>>();
      assertNotNull(treeSet0);
      
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence((WeightedGraph<Integer>) denseWeightedGraph0, (Set<Edge<Integer>>) treeSet0, (Set<Edge<Integer>>) treeSet0);
      
      } catch(ClassCastException e) {
         //
         // net.mooctest.Edge cannot be cast to java.lang.Comparable
         //
         assertTrue(e instanceof ClassCastException);
      }
  }

  @Test(timeout = 1000)
  public void testd153b707_bc3f_4660_b192_5daa303e5e6b05()  throws Throwable  {
      double[][] doubleArray0 = new double[6][9];
      double[] doubleArray1 = new double[2];
      doubleArray0[1] = doubleArray1;
      DenseWeightedGraph<Integer> denseWeightedGraph0 = DenseWeightedGraph.from(doubleArray0);
      assertNotNull(denseWeightedGraph0);
      assertEquals(6, doubleArray0.length);
      
      Integer integer0 = new Integer(1029);
      assertEquals(1029, (int)integer0);
      assertNotNull(integer0);
      
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence((WeightedGraph<Integer>) denseWeightedGraph0, integer0);
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         assertTrue(e instanceof ArrayIndexOutOfBoundsException);
      }
  }

  @Test(timeout = 1000)
  public void testb28e74f4_881d_49cb_8739_e528f6c8a91806()  throws Throwable  {
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence((WeightedGraph<Arborescence<Object>>) null);
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertTrue(e instanceof NullPointerException);
      }
  }

  @Test(timeout = 1000)
  public void testeac81503_e798_4202_9821_fb192340471907()  throws Throwable  {
      double[][] doubleArray0 = new double[5][9];
      double[] doubleArray1 = new double[1];
      doubleArray0[1] = doubleArray1;
      DenseWeightedGraph<Integer> denseWeightedGraph0 = DenseWeightedGraph.from(doubleArray0);
      assertNotNull(denseWeightedGraph0);
      assertEquals(5, doubleArray0.length);
      
      // Undeclared exception!
      try { 
        ChuLiuEdmonds.getMaxArborescence((WeightedGraph<Integer>) denseWeightedGraph0);
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         assertTrue(e instanceof ArrayIndexOutOfBoundsException);
      }
  }

  @Test(timeout = 1000)
  public void testba6f610d_3818_49c0_a574_1a427e36f8ac08()  throws Throwable  {
      Class<String> class0 = String.class;
      ServiceLoader<String> serviceLoader0 = ServiceLoader.loadInstalled(class0);
      assertEquals("java.util.ServiceLoader[java.lang.String]", serviceLoader0.toString());
      assertNotNull(serviceLoader0);
      
      double[][] doubleArray0 = new double[0][8];
      DenseWeightedGraph<String> denseWeightedGraph0 = DenseWeightedGraph.from((Iterable<String>) serviceLoader0, doubleArray0);
      assertEquals("java.util.ServiceLoader[java.lang.String]", serviceLoader0.toString());
      assertNotNull(denseWeightedGraph0);
      assertEquals(0, doubleArray0.length);
      
      ChuLiuEdmonds.PartialSolution<String> chuLiuEdmonds_PartialSolution0 = ChuLiuEdmonds.PartialSolution.initialize((WeightedGraph<String>) denseWeightedGraph0);
      assertEquals("java.util.ServiceLoader[java.lang.String]", serviceLoader0.toString());
      assertNotNull(chuLiuEdmonds_PartialSolution0);
      assertEquals(0, doubleArray0.length);
      
      Set<String> set0 = chuLiuEdmonds_PartialSolution0.getNodes();
      assertEquals("java.util.ServiceLoader[java.lang.String]", serviceLoader0.toString());
      assertTrue(set0.isEmpty());
      assertEquals(0, set0.size());
      assertNotNull(set0);
      assertEquals(0, doubleArray0.length);
  }

  @Test(timeout = 1000)
  public void testcab0383f_efe5_46a0_ac9d_517cd096b49c09()  throws Throwable  {
      ArrayList<Weighted<Edge<Locale.Category>>> arrayList0 = new ArrayList<Weighted<Edge<Locale.Category>>>();
      assertEquals(0, arrayList0.size());
      assertTrue(arrayList0.isEmpty());
      assertNotNull(arrayList0);
      
      SparseWeightedGraph<Locale.Category> sparseWeightedGraph0 = SparseWeightedGraph.from((Iterable<Weighted<Edge<Locale.Category>>>) arrayList0);
      assertEquals(0, arrayList0.size());
      assertTrue(arrayList0.isEmpty());
      assertNotNull(sparseWeightedGraph0);
      
      ChuLiuEdmonds.PartialSolution<Locale.Category> chuLiuEdmonds_PartialSolution0 = ChuLiuEdmonds.PartialSolution.initialize((WeightedGraph<Locale.Category>) sparseWeightedGraph0);
      assertEquals(0, arrayList0.size());
      assertTrue(arrayList0.isEmpty());
      assertNotNull(chuLiuEdmonds_PartialSolution0);
      
      Locale.Category locale_Category0 = Locale.Category.FORMAT;
      Arborescence<Locale.Category> arborescence0 = Arborescence.empty();
      assertNotNull(arborescence0);
      
      Optional<ExclusiveEdge<Locale.Category>> optional0 = chuLiuEdmonds_PartialSolution0.popBestEdge(locale_Category0, arborescence0);
      assertEquals(0, arrayList0.size());
      assertTrue(arrayList0.isEmpty());
      assertNotNull(optional0);
  }

  @Test(timeout = 1000)
  public void test7a0d4d65_484e_4d41_8c6d_57065f10ce7110()  throws Throwable  {
      double[][] doubleArray0 = new double[2][4];
      DenseWeightedGraph<Integer> denseWeightedGraph0 = DenseWeightedGraph.from(doubleArray0);
      LinkedHashSet<Edge<Integer>> linkedHashSet0 = new LinkedHashSet<Edge<Integer>>();
      Weighted<Arborescence<Integer>> weighted0 = ChuLiuEdmonds.getMaxArborescence((WeightedGraph<Integer>) denseWeightedGraph0, (Set<Edge<Integer>>) linkedHashSet0, (Set<Edge<Integer>>) linkedHashSet0);
      assertEquals(0.0, weighted0.weight, 0.01);
  }

  @Test(timeout = 1000)
  public void test012fca78_5be7_40d5_b1d1_f609f32d7a5011()  throws Throwable  {
      double[][] doubleArray0 = new double[1][3];
      DenseWeightedGraph<Integer> denseWeightedGraph0 = DenseWeightedGraph.from(doubleArray0);
      ChuLiuEdmonds.PartialSolution<Integer> chuLiuEdmonds_PartialSolution0 = ChuLiuEdmonds.PartialSolution.initialize((WeightedGraph<Integer>) denseWeightedGraph0);
      assertNotNull(chuLiuEdmonds_PartialSolution0);
  }

  @Test(timeout = 1000)
  public void test1350766e_d6bc_4ce4_b913_a0871d76e46012()  throws Throwable  {
      Locale.Category locale_Category0 = Locale.Category.FORMAT;
      EnumSet<Locale.Category> enumSet0 = EnumSet.of(locale_Category0);
      double[][] doubleArray0 = new double[1][4];
      DenseWeightedGraph<Locale.Category> denseWeightedGraph0 = DenseWeightedGraph.from((Iterable<Locale.Category>) enumSet0, doubleArray0);
      Weighted<Arborescence<Locale.Category>> weighted0 = ChuLiuEdmonds.getMaxArborescence((WeightedGraph<Locale.Category>) denseWeightedGraph0);
      assertEquals(0.0, weighted0.weight, 0.01);
  }


  @Test(timeout = 1000)
  public void test447bb971_a9d8_4408_b160_152df2378d9115()  throws Throwable  {
      ChuLiuEdmonds chuLiuEdmonds0 = new ChuLiuEdmonds();
  }
}
