/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 30 05:19:03 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import net.mooctest.Edge;
import net.mooctest.ExclusiveEdge;
import org.junit.runner.RunWith;

public class ExclusiveEdge_ESTest {
 
}
